### ISSUE TITLE
Whitelist / Blacklist webpages to censor or not

### ISSUE THREAD

**Issue by MKrabs** [AidanSpeakss/streamer-mode-for-firefox#5]
Some sort of black- or whitelisting webpages could be nice, if you want to show sensitive data / who you are.

Possibly an option in the add-on window to toggle between: `All` - `none` - `Whitelist` - `Blacklist`

**Comment by AidanSpeakss** [comment]
The most important part of this enhancement, a whitelist, has been added in v1.7.1 and v1.7.1c (both chrome and firefox releases). I don't think I'm going to add the `All - none - Whitelist - Blacklist` right now, but feel free to open another issue for that feature in specific, eventually I will get to it.

Thanks again for all the helpful suggestions and feedback!
