### ISSUE TITLE
Regex as a keyword

### ISSUE THREAD

**Issue by MKrabs** [AidanSpeakss/streamer-mode-for-firefox#6]
Well.. not much to say, except adding regex capabilities to the keywords.

- xxCoolName[0-9]+xx

**Comment by ConniBug** [comment]
I honestly think thats already an unintended feature that already exists, as it just takes your input and parses it straght to the RegExp func

https://github.com/AidanSpeakss/streamer-mode-for-firefox/blob/df05b39a07ca31bab8431466755920f45fd64845/src/background.js#L28

**Comment by AidanSpeakss** [comment]
> 

I think you are right about this, I'll try testing out a bit of regex.

**Comment by AidanSpeakss** [comment]
Yeah, that's hilarious, this is already a feature then. Although I suspect it causes bugs, as there is no distinction between regex and non-regex. I'll add a separate regex field quickly, to solve any problems this may have caused.

**Comment by AidanSpeakss** [comment]
This feature has been added and will be in the 1.7 release.

**Comment by ConniBug** [comment]
Sorry to reopen this, but in additon to what you have already added what about having the abbility to disable/enable the case sensitivity of regex as currently its hard coded?

**Comment by AidanSpeakss** [comment]
> 

If you create a new issue with that specific suggestion, you can just link back to this one.
